apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: default
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      restartPolicy: Always
      containers:
      - name: mongo
        image: 757131707204.dkr.ecr.us-east-1.amazonaws.com/node:mongo
        securityContext:
         privileged: true
        ports:
        - containerPort: 27017
        imagePullPolicy: Always
#        resources:
#          requests:
#            memory: "256Mi"
#            cpu: "250m"
#          limits:
#            memory: "256Mi"
#            cpu: "250m"
